/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CravingsRouteImport } from './routes/cravings'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as RestaurantRestaurantIdRouteImport } from './routes/restaurant.$restaurantId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MealMealIdRouteImport } from './routes/meal.$mealId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CravingsRoute = CravingsRouteImport.update({
  id: '/cravings',
  path: '/cravings',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRestaurantIdRoute = RestaurantRestaurantIdRouteImport.update({
  id: '/restaurant/$restaurantId',
  path: '/restaurant/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealMealIdRoute = MealMealIdRouteImport.update({
  id: '/meal/$mealId',
  path: '/meal/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/cravings': typeof CravingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/cravings': typeof CravingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/cart': typeof CartRoute
  '/cravings': typeof CravingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/meal/$mealId': typeof MealMealIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/cart'
    | '/cravings'
    | '/discover'
    | '/login'
    | '/nearby'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/meal/$mealId'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/business'
    | '/cart'
    | '/cravings'
    | '/discover'
    | '/login'
    | '/nearby'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/meal/$mealId'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/cart'
    | '/cravings'
    | '/discover'
    | '/login'
    | '/nearby'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/meal/$mealId'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRoute
  CartRoute: typeof CartRoute
  CravingsRoute: typeof CravingsRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  MealMealIdRoute: typeof MealMealIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RestaurantRestaurantIdRoute: typeof RestaurantRestaurantIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cravings': {
      id: '/cravings'
      path: '/cravings'
      fullPath: '/cravings'
      preLoaderRoute: typeof CravingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$restaurantId': {
      id: '/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof RestaurantRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$mealId': {
      id: '/meal/$mealId'
      path: '/meal/$mealId'
      fullPath: '/meal/$mealId'
      preLoaderRoute: typeof MealMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRoute,
  CartRoute: CartRoute,
  CravingsRoute: CravingsRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  MealMealIdRoute: MealMealIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RestaurantRestaurantIdRoute: RestaurantRestaurantIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
